from classes import *
import colors
import pygame
class dotEngine:
    def __init__(self, surface, player_rect):
        self.surface = surface
        self.dot0 = dot(self.surface)
        self.dot1 = dot(self.surface)
        self.dot2 = dot(self.surface)
        self.dot3 = dot(self.surface)
        self.dot4 = dot(self.surface)
        self.dot5 = dot(self.surface)
        self.dot6 = dot(self.surface)
        self.dot7 = dot(self.surface)
        self.dot8 = dot(self.surface)
        self.dot9 = dot(self.surface)
        self.dot10 = dot(self.surface)
        self.dot11 = dot(self.surface)
        self.dot12 = dot(self.surface)
        self.dot13 = dot(self.surface)
        self.dot14 = dot(self.surface)
        self.dot15 = dot(self.surface)
        self.dot16 = dot(self.surface)
        self.dot17 = dot(self.surface)
        self.dot18 = dot(self.surface)
        self.dot19 = dot(self.surface)
        self.dot20 = dot(self.surface)
        self.dot21 = dot(self.surface)
        self.dot22 = dot(self.surface)
        self.dot23 = dot(self.surface)
        self.dot24 = dot(self.surface)
        self.dot25 = dot(self.surface)
        self.dot26 = dot(self.surface)
        self.dot27 = dot(self.surface)
        self.dot28 = dot(self.surface)
        self.dot29 = dot(self.surface)
        self.dot30 = dot(self.surface)
        self.dot31 = dot(self.surface)
        self.dot32 = dot(self.surface)
        self.dot33 = dot(self.surface)
        self.dot34 = dot(self.surface)
        self.dot35 = dot(self.surface)
        self.dot36 = dot(self.surface)
        self.dot37 = dot(self.surface)
        self.dot38 = dot(self.surface)
        self.dot39 = dot(self.surface)
        self.dot40 = dot(self.surface)
        self.dot41 = dot(self.surface)
        self.dot42 = dot(self.surface)
        self.dot43 = dot(self.surface)
        self.dot44 = dot(self.surface)
        self.dot45 = dot(self.surface)
        self.dot46 = dot(self.surface)
        self.dot47 = dot(self.surface)
        self.dot48 = dot(self.surface)
        self.dot49 = dot(self.surface)
        self.dot50 = dot(self.surface)
        self.dot51 = dot(self.surface)
        self.dot52 = dot(self.surface)
        self.dot53 = dot(self.surface)
        self.dot54 = dot(self.surface)
        self.dot55 = dot(self.surface)
        self.dot56 = dot(self.surface)
        self.dot57 = dot(self.surface)
        self.dot58 = dot(self.surface)
        self.dot59 = dot(self.surface)
        self.dot60 = dot(self.surface)
        self.dot61 = dot(self.surface)
        self.dot62 = dot(self.surface)
        self.dot63 = dot(self.surface)
        self.dot64 = dot(self.surface)
        self.dot65 = dot(self.surface)
        self.dot66 = dot(self.surface)
        self.dot67 = dot(self.surface)
        self.dot68 = dot(self.surface)
        self.dot69 = dot(self.surface)
        self.dot70 = dot(self.surface)
        self.dot71 = dot(self.surface)
        self.dot72 = dot(self.surface)
        self.dot73 = dot(self.surface)
        self.dot74 = dot(self.surface)
        self.dot75 = dot(self.surface)
        self.dot76 = dot(self.surface)
        self.dot77 = dot(self.surface)
        self.dot78 = dot(self.surface)
        self.dot79 = dot(self.surface)
        self.dot80 = dot(self.surface)
        self.dot81 = dot(self.surface)
        self.dot82 = dot(self.surface)
        self.dot83 = dot(self.surface)
        self.dot84 = dot(self.surface)
        self.dot85 = dot(self.surface)
        self.dot86 = dot(self.surface)
        self.dot87 = dot(self.surface)
        self.dot88 = dot(self.surface)
        self.dot89 = dot(self.surface)
        self.dot90 = dot(self.surface)
        self.dot91 = dot(self.surface)
        self.dot92 = dot(self.surface)
        self.dot93 = dot(self.surface)
        self.dot94 = dot(self.surface)
        self.dot95 = dot(self.surface)
        self.dot96 = dot(self.surface)
        self.dot97 = dot(self.surface)
        self.dot98 = dot(self.surface)
        self.dot99 = dot(self.surface)
        self.PlayerRECT = player_rect

    def draw(self):

        self.dot0.draw()
        self.dot1.draw()
        self.dot2.draw()
        self.dot3.draw()
        self.dot4.draw()
        self.dot5.draw()
        self.dot6.draw()
        self.dot7.draw()
        self.dot8.draw()
        self.dot9.draw()
        self.dot10.draw()
        self.dot11.draw()
        self.dot12.draw()
        self.dot13.draw()
        self.dot14.draw()
        self.dot15.draw()
        self.dot16.draw()
        self.dot17.draw()
        self.dot18.draw()
        self.dot19.draw()
        self.dot20.draw()
        self.dot21.draw()
        self.dot22.draw()
        self.dot23.draw()
        self.dot24.draw()
        self.dot25.draw()
        self.dot26.draw()
        self.dot27.draw()
        self.dot28.draw()
        self.dot29.draw()
        self.dot30.draw()
        self.dot31.draw()
        self.dot32.draw()
        self.dot33.draw()
        self.dot34.draw()
        self.dot35.draw()
        self.dot36.draw()
        self.dot37.draw()
        self.dot38.draw()
        self.dot39.draw()
        self.dot40.draw()
        self.dot41.draw()
        self.dot42.draw()
        self.dot43.draw()
        self.dot44.draw()
        self.dot45.draw()
        self.dot46.draw()
        self.dot47.draw()
        self.dot48.draw()
        self.dot49.draw()
        self.dot50.draw()
        self.dot51.draw()
        self.dot52.draw()
        self.dot53.draw()
        self.dot54.draw()
        self.dot55.draw()
        self.dot56.draw()
        self.dot57.draw()
        self.dot58.draw()
        self.dot59.draw()
        self.dot60.draw()
        self.dot61.draw()
        self.dot62.draw()
        self.dot63.draw()
        self.dot64.draw()
        self.dot65.draw()
        self.dot66.draw()
        self.dot67.draw()
        self.dot68.draw()
        self.dot69.draw()
        self.dot70.draw()
        self.dot71.draw()
        self.dot72.draw()
        self.dot73.draw()
        self.dot74.draw()
        self.dot75.draw()
        self.dot76.draw()
        self.dot77.draw()
        self.dot78.draw()
        self.dot79.draw()
        self.dot80.draw()
        self.dot81.draw()
        self.dot82.draw()
        self.dot83.draw()
        self.dot84.draw()
        self.dot85.draw()
        self.dot86.draw()
        self.dot87.draw()
        self.dot88.draw()
        self.dot89.draw()
        self.dot90.draw()
        self.dot91.draw()
        self.dot92.draw()
        self.dot93.draw()
        self.dot94.draw()
        self.dot95.draw()
        self.dot96.draw()
        self.dot97.draw()
        self.dot98.draw()
        self.dot99.draw()

    def pos_check(self,scoreObj, playerFunc):


        self.check_engine(self.dot0, scoreObj, playerFunc)
        self.check_engine(self.dot1, scoreObj, playerFunc)
        self.check_engine(self.dot2, scoreObj, playerFunc)
        self.check_engine(self.dot3, scoreObj, playerFunc)
        self.check_engine(self.dot4, scoreObj, playerFunc)
        self.check_engine(self.dot5, scoreObj, playerFunc)
        self.check_engine(self.dot6, scoreObj, playerFunc)
        self.check_engine(self.dot7, scoreObj, playerFunc)
        self.check_engine(self.dot8, scoreObj, playerFunc)
        self.check_engine(self.dot9, scoreObj, playerFunc)
        self.check_engine(self.dot10, scoreObj, playerFunc)
        self.check_engine(self.dot11, scoreObj, playerFunc)
        self.check_engine(self.dot12, scoreObj, playerFunc)
        self.check_engine(self.dot13, scoreObj, playerFunc)
        self.check_engine(self.dot14, scoreObj, playerFunc)
        self.check_engine(self.dot15, scoreObj, playerFunc)
        self.check_engine(self.dot16, scoreObj, playerFunc)
        self.check_engine(self.dot17, scoreObj, playerFunc)
        self.check_engine(self.dot18, scoreObj, playerFunc)
        self.check_engine(self.dot19, scoreObj, playerFunc)
        self.check_engine(self.dot20, scoreObj, playerFunc)
        self.check_engine(self.dot21, scoreObj, playerFunc)
        self.check_engine(self.dot22, scoreObj, playerFunc)
        self.check_engine(self.dot23, scoreObj, playerFunc)
        self.check_engine(self.dot24, scoreObj, playerFunc)
        self.check_engine(self.dot25, scoreObj, playerFunc)
        self.check_engine(self.dot26, scoreObj, playerFunc)
        self.check_engine(self.dot27, scoreObj, playerFunc)
        self.check_engine(self.dot28, scoreObj, playerFunc)
        self.check_engine(self.dot29, scoreObj, playerFunc)
        self.check_engine(self.dot30, scoreObj, playerFunc)
        self.check_engine(self.dot31, scoreObj, playerFunc)
        self.check_engine(self.dot32, scoreObj, playerFunc)
        self.check_engine(self.dot33, scoreObj, playerFunc)
        self.check_engine(self.dot34, scoreObj, playerFunc)
        self.check_engine(self.dot35, scoreObj, playerFunc)
        self.check_engine(self.dot36, scoreObj, playerFunc)
        self.check_engine(self.dot37, scoreObj, playerFunc)
        self.check_engine(self.dot38, scoreObj, playerFunc)
        self.check_engine(self.dot39, scoreObj, playerFunc)
        self.check_engine(self.dot40, scoreObj, playerFunc)
        self.check_engine(self.dot41, scoreObj, playerFunc)
        self.check_engine(self.dot42, scoreObj, playerFunc)
        self.check_engine(self.dot43, scoreObj, playerFunc)
        self.check_engine(self.dot44, scoreObj, playerFunc)
        self.check_engine(self.dot45, scoreObj, playerFunc)
        self.check_engine(self.dot46, scoreObj, playerFunc)
        self.check_engine(self.dot47, scoreObj, playerFunc)
        self.check_engine(self.dot48, scoreObj, playerFunc)
        self.check_engine(self.dot49, scoreObj, playerFunc)
        self.check_engine(self.dot50, scoreObj, playerFunc)
        self.check_engine(self.dot51, scoreObj, playerFunc)
        self.check_engine(self.dot52, scoreObj, playerFunc)
        self.check_engine(self.dot53, scoreObj, playerFunc)
        self.check_engine(self.dot54, scoreObj, playerFunc)
        self.check_engine(self.dot55, scoreObj, playerFunc)
        self.check_engine(self.dot56, scoreObj, playerFunc)
        self.check_engine(self.dot57, scoreObj, playerFunc)
        self.check_engine(self.dot58, scoreObj, playerFunc)
        self.check_engine(self.dot59, scoreObj, playerFunc)
        self.check_engine(self.dot60, scoreObj, playerFunc)
        self.check_engine(self.dot61, scoreObj, playerFunc)
        self.check_engine(self.dot62, scoreObj, playerFunc)
        self.check_engine(self.dot63, scoreObj, playerFunc)
        self.check_engine(self.dot64, scoreObj, playerFunc)
        self.check_engine(self.dot65, scoreObj, playerFunc)
        self.check_engine(self.dot66, scoreObj, playerFunc)
        self.check_engine(self.dot67, scoreObj, playerFunc)
        self.check_engine(self.dot68, scoreObj, playerFunc)
        self.check_engine(self.dot69, scoreObj, playerFunc)
        self.check_engine(self.dot70, scoreObj, playerFunc)
        self.check_engine(self.dot71, scoreObj, playerFunc)
        self.check_engine(self.dot72, scoreObj, playerFunc)
        self.check_engine(self.dot73, scoreObj, playerFunc)
        self.check_engine(self.dot74, scoreObj, playerFunc)
        self.check_engine(self.dot75, scoreObj, playerFunc)
        self.check_engine(self.dot76, scoreObj, playerFunc)
        self.check_engine(self.dot77, scoreObj, playerFunc)
        self.check_engine(self.dot78, scoreObj, playerFunc)
        self.check_engine(self.dot79, scoreObj, playerFunc)
        self.check_engine(self.dot80, scoreObj, playerFunc)
        self.check_engine(self.dot81, scoreObj, playerFunc)
        self.check_engine(self.dot82, scoreObj, playerFunc)
        self.check_engine(self.dot83, scoreObj, playerFunc)
        self.check_engine(self.dot84, scoreObj, playerFunc)
        self.check_engine(self.dot85, scoreObj, playerFunc)
        self.check_engine(self.dot86, scoreObj, playerFunc)
        self.check_engine(self.dot87, scoreObj, playerFunc)
        self.check_engine(self.dot88, scoreObj, playerFunc)
        self.check_engine(self.dot89, scoreObj, playerFunc)
        self.check_engine(self.dot90, scoreObj, playerFunc)
        self.check_engine(self.dot91, scoreObj, playerFunc)
        self.check_engine(self.dot92, scoreObj, playerFunc)
        self.check_engine(self.dot93, scoreObj, playerFunc)
        self.check_engine(self.dot94, scoreObj, playerFunc)
        self.check_engine(self.dot95, scoreObj, playerFunc)
        self.check_engine(self.dot96, scoreObj, playerFunc)
        self.check_engine(self.dot97, scoreObj, playerFunc)
        self.check_engine(self.dot98, scoreObj, playerFunc)
        self.check_engine(self.dot99, scoreObj, playerFunc)

    def check_engine(self, the_dot, scoreAdd, player):
        if the_dot.rect.colliderect(self.PlayerRECT):
            the_dot.generate()
            scoreAdd.add(1)
            the_dot.draw()
            player.enlarge()


    def rectUpdate(self, playerRect):
        self.PlayerRECT = playerRect

    def update(self, scoreObj, playerFunc):
        self.pos_check(scoreObj, playerFunc)
        self.draw()

class playerEngine:
    def __init__(self, surface):
        self.Player = playerObj(surface, colors.azure3, 10, 10, 335, 340)

    def enlarge(self):
        if self.Player.rect[2] < 25:
            self.Player.rect[2] += 2
            self.Player.rect[3] += 2
        elif self.Player.rect[2] < 65:
            self.Player.rect[2] += 1
            self.Player.rect[3] += 1

    def deEnlarge(self, amount):
        self.Player.rect[2] -= amount
        self.Player.rect[3] -= amount

    def movement(self):
        key = pygame.key.get_pressed()
        if key[pygame.K_a] and self.Player.rect[0] > 0:
            self.Player.rect.move_ip((-(self.Player.rect[3]/2)), 0)

        if key[pygame.K_d] and (self.Player.rect[0] + self.Player.rect[2]) < 700:
            self.Player.rect.move_ip((self.Player.rect[3]/2), 0)

        if key[pygame.K_w] and self.Player.rect[1] > 50:
            self.Player.rect.move_ip(0, (-(self.Player.rect[2]/2)))

        if key[pygame.K_s] and (self.Player.rect[1] + self.Player.rect[3]) < 700:
            self.Player.rect.move_ip(0, (self.Player.rect[2]/2))

    def draw(self):
        self.movement()
        self.Player.draw()

class virusEngine:
    def __init__(self, surface, player):
        self.surface = surface
        self.playerInstance = player
        ###
        self.virusObj_0 = virusDot(surface)

    def drawLogic(self, virusObj):
        if self.playerInstance.Player.rect[2] >= virusObj.rect[2]:
            virusObj.draw()
            self.playerInstance.draw()
            return True
        else:
            self.playerInstance.draw()
            virusObj.draw()
            return False
    def draw(self):
        self.drawLogic(self.virusObj_0)

    def mass_check(self, scoreboard):
        self.check_engine(self.virusObj_0, scoreboard)

    def check_engine(self, selfVirus, scoreboard):
        if selfVirus.rect.colliderect(self.playerInstance.Player.rect) and self.drawLogic(selfVirus):
            selfVirus.generate()
            self.playerInstance.deEnlarge(10)
        elif selfVirus.rect.colliderect(self.playerInstance.Player.rect) and self.playerInstance.Player.rect[2] > 1:
            self.playerInstance.deEnlarge(5)

    def update(self, scoreObj):
        self.mass_check(scoreObj)
        self.draw()
